// Generated by CoffeeScript 1.4.0
(function() {
  var $, BACKSPACE, BaseClass, DELETE, END, MOUSE_EVENTS, MOVE, Mark, MarkingSurface, Raphael, START, TAB, TOUCH, Tool, ToolControls, doc, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __slice = [].slice,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  $ = window.jQuery;

  Raphael = window.Raphael;

  doc = $(document);

  TOUCH = 'Touch' in window;

  _ref = TOUCH ? ['touchstart', 'touchmove', 'touchend'] : ['mousedown', 'mousemove', 'mouseup'], START = _ref[0], MOVE = _ref[1], END = _ref[2];

  BACKSPACE = 8;

  DELETE = 46;

  TAB = 9;

  BaseClass = (function() {
    var method, _fn, _i, _len, _ref1,
      _this = this;

    BaseClass.prototype.jQueryEventProxy = null;

    function BaseClass(params) {
      var property, value;
      if (params == null) {
        params = {};
      }
      for (property in params) {
        if (!__hasProp.call(params, property)) continue;
        value = params[property];
        if (property in this) {
          this[property] = value;
        }
      }
      this.jQueryEventProxy = $({});
    }

    BaseClass.prototype.destroy = function() {
      this.trigger('destroy');
      return this.off();
    };

    _ref1 = ['on', 'one', 'trigger', 'off'];
    _fn = function(method) {
      return BaseClass.prototype[method] = function() {
        var _ref2;
        return (_ref2 = this.jQueryEventProxy)[method].apply(_ref2, arguments);
      };
    };
    for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
      method = _ref1[_i];
      _fn(method);
    }

    return BaseClass;

  }).call(this);

  Mark = (function(_super) {

    __extends(Mark, _super);

    function Mark() {
      return Mark.__super__.constructor.apply(this, arguments);
    }

    Mark.prototype.set = function(property, value, _arg) {
      var fromMany, map, setter;
      fromMany = (_arg != null ? _arg : {}).fromMany;
      if (typeof property === 'string') {
        setter = this["set " + property];
        this[property] = setter ? setter.call(this, value) : value;
      } else {
        map = property;
        for (property in map) {
          value = map[property];
          this.set(property, value, {
            fromMany: true
          });
        }
      }
      if (!fromMany) {
        return this.trigger('change', property, value);
      }
    };

    Mark.prototype.toJSON = function() {
      var property, result, value;
      result = {};
      for (property in this) {
        value = this[property];
        if (property === 'jQueryEventProxy') {
          continue;
        }
        if (typeof value === 'function') {
          continue;
        }
        result[property] = value;
      }
      return result;
    };

    return Mark;

  })(BaseClass);

  ToolControls = (function(_super) {

    __extends(ToolControls, _super);

    ToolControls.prototype.tool = null;

    ToolControls.prototype.el = null;

    ToolControls.prototype.handle = null;

    ToolControls.prototype.label = null;

    ToolControls.prototype.deleteButton = null;

    ToolControls.prototype.template = '<div class="marking-tool-controls">\n  <span class="handle"></span>\n  <span class="label"></span>\n  <button name="delete-mark">&times;</button>\n</div>';

    function ToolControls() {
      this.render = __bind(this.render, this);

      var _this = this;
      ToolControls.__super__.constructor.apply(this, arguments);
      this.el = $(this.template);
      this.handle = this.el.find('.handle');
      this.label = this.el.find('.label');
      this.deleteButton = this.el.find('button[name="delete-mark"]');
      this.el.on(START, function() {
        return _this.tool.select();
      });
      this.el.on('click', 'button[name="delete-mark"]', function(e) {
        if (_this.tool.surface.disabled) {
          return;
        }
        e.preventDefault();
        return _this.onClickDelete.apply(_this, arguments);
      });
      this.tool.on('select', function() {
        if (_this.tool.surface.disabled) {
          return;
        }
        return _this.onToolSelect.apply(_this, arguments);
      });
      this.tool.on('initial-release', function() {
        return _this.el.toggleClass('complete', _this.tool.isComplete());
      });
      this.tool.on('deselect', function() {
        if (_this.tool.surface.disabled) {
          return;
        }
        return _this.onToolDeselect.apply(_this, arguments);
      });
      this.tool.mark.on('change', function() {
        if ('label' in _this.tool.mark) {
          _this.label.html(_this.tool.mark.label);
        }
        return _this.render();
      });
      this.tool.on('destroy', function() {
        return _this.destroy();
      });
    }

    ToolControls.prototype.moveTo = function(x, y) {
      var _ref1;
      if (x instanceof Array) {
        _ref1 = x, x = _ref1[0], y = _ref1[1];
      }
      if (x > this.tool.surface.width / 2) {
        this.el.addClass('to-the-left');
        return this.el.css({
          left: '',
          position: 'absolute',
          right: this.tool.surface.width - x,
          top: y
        });
      } else {
        this.el.removeClass('to-the-left');
        return this.el.css({
          left: x,
          position: 'absolute',
          right: '',
          top: y
        });
      }
    };

    ToolControls.prototype.onToolSelect = function() {
      return this.el.addClass('selected');
    };

    ToolControls.prototype.onToolDeselect = function() {
      return this.el.removeClass('selected');
    };

    ToolControls.prototype.onClickDelete = function() {
      return this.tool.mark.destroy();
    };

    ToolControls.prototype.destroy = function() {
      this.el.off();
      return this.el.remove();
    };

    ToolControls.prototype.render = function() {};

    return ToolControls;

  })(BaseClass);

  MOUSE_EVENTS = 'mousedown mouseover mousemove mouseout mouseup\ntouchstart touchmove touchend'.split(/\s+/);

  Tool = (function(_super) {

    __extends(Tool, _super);

    Tool.Mark = Mark;

    Tool.Controls = ToolControls;

    Tool.prototype.cursors = null;

    Tool.prototype.mark = null;

    Tool.prototype.markDefaults = null;

    Tool.prototype.surface = null;

    Tool.prototype.shapeSet = null;

    Tool.prototype.controls = null;

    Tool.prototype.clicks = 0;

    function Tool() {
      var _ref1, _ref2,
        _this = this;
      Tool.__super__.constructor.apply(this, arguments);
      if ((_ref1 = this.mark) == null) {
        this.mark = new this.constructor.Mark;
      }
      if (this.markDefaults != null) {
        this.mark.set(this.markDefaults);
      }
      this.mark.on('change', function() {
        return _this.onMarkChange.apply(_this, arguments);
      });
      this.mark.on('destroy', function() {
        return _this.destroy.apply(_this, arguments);
      });
      if ((_ref2 = this.shapeSet) == null) {
        this.shapeSet = this.surface.paper.set();
      }
      this.controls = new this.constructor.Controls({
        tool: this
      });
      this.controls.el.appendTo(this.surface.container);
      this.initialize.apply(this, arguments);
    }

    Tool.prototype.addShape = function() {
      var attributes, eventName, params, shape, type, _i, _len, _ref1,
        _this = this;
      type = arguments[0], params = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      if (typeof params[params.length - 1] === 'object') {
        attributes = params.pop();
      }
      shape = (_ref1 = this.surface.paper)[type.toLowerCase()].apply(_ref1, params);
      shape.attr(attributes);
      for (_i = 0, _len = MOUSE_EVENTS.length; _i < _len; _i++) {
        eventName = MOUSE_EVENTS[_i];
        shape[eventName](function() {
          return _this.handleEvents.apply(_this, arguments);
        });
      }
      this.shapeSet.push(shape);
      return shape;
    };

    Tool.prototype.onInitialClick = function(e) {
      this.trigger('initial-click', [e]);
      return this.onFirstClick(e);
    };

    Tool.prototype.onInitialDrag = function(e) {
      return this.onFirstDrag(e);
    };

    Tool.prototype.onInitialRelease = function(e) {
      this.clicks += 1;
      this.trigger('initial-release', [e]);
      return this.onFirstRelease.apply(this, arguments);
    };

    Tool.prototype.isComplete = function() {
      return this.clicks === 1;
    };

    Tool.prototype.handleEvents = function(e) {
      var eventName, isArray, name, onDrag, onNamedDrag, property, shape, target, value, _ref1, _ref2, _ref3,
        _this = this;
      if (this.surface.disabled) {
        return;
      }
      eventName = e.type;
      target = e.target || e.srcElement;
      shape = this.surface.paper.getById(target.raphaelid);
      name = '*';
      for (property in this) {
        value = this[property];
        isArray = value instanceof Array || value instanceof this.shapeSet.constructor;
        if ((value === shape) || (isArray && __indexOf.call(value, shape) >= 0)) {
          name = property;
        }
      }
      if ((_ref1 = this["on " + eventName]) != null) {
        _ref1.call(this, e, shape);
      }
      if ((_ref2 = this["on " + eventName + " " + name]) != null) {
        _ref2.call(this, e, shape);
      }
      switch (eventName) {
        case 'mouseover':
          return this.surface.container.css({
            cursor: (_ref3 = this.cursors) != null ? _ref3[name] : void 0
          });
        case 'mouseout':
          return this.surface.container.css({
            cursor: ''
          });
        case START:
          e.preventDefault();
          this.select();
          if ('on drag' in this) {
            onDrag = function() {
              return _this['on drag'].apply(_this, __slice.call(arguments).concat([shape]));
            };
            doc.on(MOVE, onDrag);
            doc.one(END, function() {
              return doc.off(MOVE, onDrag);
            });
          }
          if (name && ("on drag " + name) in this) {
            onNamedDrag = function() {
              return _this["on drag " + name].apply(_this, __slice.call(arguments).concat([shape]));
            };
            doc.on(MOVE, onNamedDrag);
            return doc.one(END, function() {
              return doc.off(MOVE, onNamedDrag);
            });
          }
      }
    };

    Tool.prototype.mouseOffset = function() {
      var _ref1;
      return (_ref1 = this.surface).mouseOffset.apply(_ref1, arguments);
    };

    Tool.prototype.onMarkChange = function() {
      return this.render.apply(this, arguments);
    };

    Tool.prototype.select = function() {
      this.shapeSet.attr({
        opacity: 1
      });
      this.shapeSet.toFront();
      return this.trigger('select', arguments);
    };

    Tool.prototype.deselect = function() {
      this.shapeSet.attr({
        opacity: 0.5
      });
      return this.trigger('deselect', arguments);
    };

    Tool.prototype.destroy = function() {
      var _this = this;
      Tool.__super__.destroy.apply(this, arguments);
      this.surface.container.focus();
      return this.shapeSet.animate({
        opacity: 0,
        r: 0,
        'stroke-width': 0
      }, 250, 'ease-in', function() {
        return _this.shapeSet.remove();
      });
    };

    Tool.prototype.initialize = function() {};

    Tool.prototype.onFirstClick = function(e) {};

    Tool.prototype.onFirstDrag = function(e) {};

    Tool.prototype.onFirstRelease = function(e) {};

    Tool.prototype.render = function() {};

    return Tool;

  })(BaseClass);

  MarkingSurface = (function(_super) {

    __extends(MarkingSurface, _super);

    MarkingSurface.prototype.tool = Tool;

    MarkingSurface.prototype.container = null;

    MarkingSurface.prototype.className = 'marking-surface';

    MarkingSurface.prototype.width = 400;

    MarkingSurface.prototype.height = 300;

    MarkingSurface.prototype.background = '';

    MarkingSurface.prototype.paper = null;

    MarkingSurface.prototype.image = null;

    MarkingSurface.prototype.marks = null;

    MarkingSurface.prototype.tools = null;

    MarkingSurface.prototype.zoomBy = 1;

    MarkingSurface.prototype.panX = 0;

    MarkingSurface.prototype.panY = 0;

    MarkingSurface.prototype.selection = null;

    MarkingSurface.prototype.disabled = false;

    function MarkingSurface(params) {
      var _ref1, _ref2, _ref3, _ref4,
        _this = this;
      if (params == null) {
        params = {};
      }
      MarkingSurface.__super__.constructor.apply(this, arguments);
      if ((_ref1 = this.container) == null) {
        this.container = document.createElement('div');
      }
      this.container = $(this.container);
      this.container.addClass(this.className);
      this.container.attr({
        tabindex: 0,
        unselectable: true
      });
      this.container.on('blur', function() {
        return _this.onBlur.apply(_this, arguments);
      });
      this.container.on('focus', function() {
        return _this.onFocus.apply(_this, arguments);
      });
      if (this.container.parents().length !== 0) {
        if (!('width' in params)) {
          this.width = this.container.width() || this.width;
        }
        if (!('height' in params)) {
          this.height = this.container.height() || this.height;
        }
      }
      if ((_ref2 = this.paper) == null) {
        this.paper = Raphael(this.container.get(0), this.width, this.height);
      }
      this.image = this.paper.image('about:blank', 0, 0, this.width, this.height);
      setTimeout(function() {
        return _this.image.attr({
          src: _this.background
        });
      });
      if ((_ref3 = this.marks) == null) {
        this.marks = [];
      }
      if ((_ref4 = this.tools) == null) {
        this.tools = [];
      }
      if (this.disabled) {
        disable();
      }
      this.container.on(START, function() {
        return _this.onMouseDown.apply(_this, arguments);
      });
      this.container.on(MOVE, function() {
        return _this.onMouseMove.apply(_this, arguments);
      });
      this.container.on('keydown', function() {
        return _this.onKeyDown.apply(_this, arguments);
      });
    }

    MarkingSurface.prototype.resize = function(width, height) {
      this.width = width;
      this.height = height;
      this.paper.setSize(this.width, this.height);
      return this.image.attr({
        width: this.width,
        height: this.height
      });
    };

    MarkingSurface.prototype.zoom = function(zoomBy) {
      this.zoomBy = zoomBy != null ? zoomBy : 1;
      return this.pan();
    };

    MarkingSurface.prototype.pan = function(panX, panY) {
      var tool, _i, _len, _ref1, _results;
      this.panX = panX != null ? panX : this.panX;
      this.panY = panY != null ? panY : this.panY;
      this.panX = Math.min(this.panX, this.width, this.width - (this.width / this.zoomBy));
      this.panY = Math.min(this.panY, this.height, this.height - (this.height / this.zoomBy));
      this.paper.setViewBox(this.panX, this.panY, this.width / this.zoomBy, this.height / this.zoomBy);
      _ref1 = this.tools;
      _results = [];
      for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
        tool = _ref1[_i];
        _results.push(tool.render());
      }
      return _results;
    };

    MarkingSurface.prototype.onMouseMove = function(e) {
      var x, y, _ref1;
      if (this.zoomBy === 1) {
        return;
      }
      _ref1 = this.mouseOffset(e), x = _ref1.x, y = _ref1.y;
      this.panX = (this.width - (this.width / this.zoomBy)) * (x / this.width);
      this.panY = (this.height - (this.height / this.zoomBy)) * (y / this.height);
      return this.pan();
    };

    MarkingSurface.prototype.onMouseDown = function(e) {
      var mark, onDrag, tool, _ref1,
        _this = this;
      if (this.disabled) {
        return;
      }
      if ((_ref1 = e.target) !== this.container.get(0) && _ref1 !== this.paper.canvas && _ref1 !== this.image.node) {
        return;
      }
      if (e.isDefaultPrevented()) {
        return;
      }
      e.preventDefault();
      $(document.activeElement).blur();
      this.container.focus();
      if (!(this.selection != null) || this.selection.isComplete()) {
        tool = new this.tool({
          surface: this
        });
        mark = tool.mark;
        this.tools.push(tool);
        this.marks.push(mark);
        tool.on('select', function() {
          var i, index, t, _i, _len, _ref2, _ref3;
          if (_this.selection !== tool) {
            if ((_ref2 = _this.selection) != null) {
              _ref2.deselect();
            }
          }
          _ref3 = _this.tools;
          for (i = _i = 0, _len = _ref3.length; _i < _len; i = ++_i) {
            t = _ref3[i];
            if (t === tool) {
              index = i;
            }
          }
          _this.tools.splice(index, 1);
          _this.tools.push(tool);
          return _this.selection = tool;
        });
        tool.on('deselect', function() {
          return _this.selection = null;
        });
        tool.on('destroy', function() {
          var i, index, t, _i, _len, _ref2, _ref3;
          _ref2 = _this.tools;
          for (i = _i = 0, _len = _ref2.length; _i < _len; i = ++_i) {
            t = _ref2[i];
            if (t === tool) {
              index = i;
            }
          }
          _this.tools.splice(index, 1);
          if (tool === _this.selection) {
            return (_ref3 = _this.tools[_this.tools.length - 1]) != null ? _ref3.select() : void 0;
          }
        });
        mark.on('destroy', function() {
          var i, index, m, _i, _len, _ref2;
          _ref2 = _this.marks;
          for (i = _i = 0, _len = _ref2.length; _i < _len; i = ++_i) {
            m = _ref2[i];
            if (m === mark) {
              index = i;
            }
          }
          _this.marks.splice(index, 1);
          return _this.trigger('destroy-mark', [mark]);
        });
        tool.select();
        this.trigger('create-mark', [mark, tool]);
      } else {
        tool = this.selection;
      }
      tool.select();
      tool.onInitialClick(e);
      onDrag = function() {
        return _this.onDrag.apply(_this, arguments);
      };
      doc.on(MOVE, onDrag);
      return doc.one(END, function() {
        _this.onRelease.apply(_this, arguments);
        return doc.off(MOVE, onDrag);
      });
    };

    MarkingSurface.prototype.onDrag = function(e) {
      e.preventDefault();
      return this.selection.onInitialDrag(e);
    };

    MarkingSurface.prototype.onRelease = function(e) {
      e.preventDefault();
      return this.selection.onInitialRelease(e);
    };

    MarkingSurface.prototype.onKeyDown = function(e) {
      var _ref1, _ref2, _ref3;
      if ($(e.target).is('input, textarea, select, button')) {
        return;
      }
      if ((_ref1 = e.which) === BACKSPACE || _ref1 === DELETE) {
        e.preventDefault();
        return (_ref2 = this.selection) != null ? _ref2.mark.destroy() : void 0;
      } else if (e.which === TAB && (this.selection != null)) {
        e.preventDefault();
        if (e.shiftKey) {
          this.tools.unshift(this.tools.pop());
        } else {
          this.tools.push(this.tools.shift());
        }
        return (_ref3 = this.tools[this.tools.length - 1]) != null ? _ref3.select() : void 0;
      }
    };

    MarkingSurface.prototype.onFocus = function() {
      var _ref1;
      return (_ref1 = this.selection) != null ? _ref1.select() : void 0;
    };

    MarkingSurface.prototype.onBlur = function() {
      var _ref1;
      if (this.container.has(document.activeElement)) {
        return;
      }
      return (_ref1 = this.selection) != null ? _ref1.deselect() : void 0;
    };

    MarkingSurface.prototype.disable = function(e) {
      var _ref1;
      this.disabled = true;
      this.container.attr({
        disabled: true
      });
      this.container.addClass('disabled');
      return (_ref1 = this.selection) != null ? _ref1.deselect() : void 0;
    };

    MarkingSurface.prototype.enable = function(e) {
      this.disabled = false;
      this.container.attr({
        disabled: false
      });
      return this.container.removeClass('disabled');
    };

    MarkingSurface.prototype.destroy = function() {
      var mark, _i, _len, _ref1;
      this.container.off().remove();
      _ref1 = this.marks;
      for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
        mark = _ref1[_i];
        mark.destroy();
      }
      return MarkingSurface.__super__.destroy.apply(this, arguments);
    };

    MarkingSurface.prototype.mouseOffset = function(e) {
      var left, originalEvent, top, _ref1;
      if ('originalEvent' in e) {
        originalEvent = e.originalEvent;
      }
      if ((originalEvent != null) && 'touches' in originalEvent) {
        e = originalEvent.touches[0];
      }
      _ref1 = this.container.offset(), left = _ref1.left, top = _ref1.top;
      left += parseFloat(this.container.css('padding-left'));
      left += (parseFloat(this.container.css('border-left-width'))) || 0;
      top += parseFloat(this.container.css('padding-top'));
      top += (parseFloat(this.container.css('border-top-width'))) || 0;
      return {
        x: e.pageX - left,
        y: e.pageY - top
      };
    };

    return MarkingSurface;

  })(BaseClass);

  MarkingSurface.Mark = Mark;

  MarkingSurface.ToolControls = ToolControls;

  MarkingSurface.Tool = Tool;

  window.MarkingSurface = MarkingSurface;

  if (typeof module !== "undefined" && module !== null) {
    if (typeof module !== "undefined" && module !== null) {
      module.exports = MarkingSurface;
    }
  }

}).call(this);
