// Generated by CoffeeScript 1.7.1
(function() {
  var DEMO_IMAGE, MarkingSurface, TOOLS, container, disabledCheckbox, getImage, marks, ms;

  MarkingSurface = window.MarkingSurface;

  TOOLS = {
    point: MarkingSurface.PointTool,
    rectangle: MarkingSurface.RectangleTool,
    ellipse: MarkingSurface.EllipseTool,
    axes: MarkingSurface.AxesTool,
    transcription: MarkingSurface.TranscriptionTool,
    magnifier: MarkingSurface.MagnifierPointTool
  };

  getImage = function(src, callback) {
    var img;
    img = new Image;
    img.onload = function() {
      return typeof callback === "function" ? callback(img) : void 0;
    };
    return img.src = src;
  };

  DEMO_IMAGE = './demo/fish.jpg';

  ms = new MarkingSurface({
    inputName: 'marks',
    tool: TOOLS[document.querySelector('input[name="tool"]:checked').value]
  });

  getImage(DEMO_IMAGE, function(_arg) {
    var height, src, width;
    src = _arg.src, width = _arg.width, height = _arg.height;
    ms.image = ms.addShape('image', {
      'xlink:href': src,
      width: width,
      height: height
    });
    ms.svg.attr({
      width: width * 0.75,
      height: height * 0.75
    });
    return ms.rescale(0, 0, width, height);
  });

  container = document.getElementById('container');

  container.appendChild(ms.el);

  marks = document.getElementById('marks');

  ms.on('marking-surface:change', function() {
    return marks.value = ms.getValue();
  });

  disabledCheckbox = document.getElementById('disabled');

  disabledCheckbox.addEventListener('change', function() {
    var checked;
    checked = disabledCheckbox.checked;
    return ms[checked ? 'disable' : 'enable']();
  });

  document.getElementById('tools').addEventListener('change', function(_arg) {
    var target;
    target = _arg.target;
    return ms.tool = TOOLS[target.value];
  });

  window.ms = ms;

}).call(this);
